INSERT INTO category_table VALUES (-1, 'Palivo');
INSERT INTO category_table VALUES (-2, 'Jidlo');
INSERT INTO category_table VALUES (-3, 'Skola');
INSERT INTO category_table VALUES (-4, 'Byt');
INSERT INTO category_table VALUES (-5, 'Nakupy');
INSERT INTO category_table VALUES (-6, 'Startovni transakce');
INSERT INTO category_table VALUES (-7, 'Ostatni');
INSERT INTO category_table VALUES (-8, 'Doprava');
INSERT INTO category_table VALUES (-9, 'Zdravi');
INSERT INTO category_table VALUES (-10, 'Mzda');
INSERT INTO category_table VALUES (-11, 'Darek');
INSERT INTO category_table VALUES (-12, 'No category');
INSERT INTO category_table VALUES (-13, 'Zabava');
INSERT INTO category_table VALUES (-14, 'Dane');